### ISSUE TITLE
Error when trying to edit an anki note in pdf add dialog

### ISSUE THREAD

**Issue by OuraN2O** [Vilhelm-Ian/anki-search-inside-add-card#14]
When my pdf was open I tried to edit an already made anki note but I had an error. 
![image](https://github.com/Vilhelm-Ian/anki-search-inside-add-card/assets/151692686/ed67f0e9-2858-4c94-8665-ea355440d4c8)

Debug info : 

```
Anki 24.04 (429bc9e1)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Linux-6.8.2-arch2-1-x86_64-with-glibc2.39

Traceback (most recent call last):
  File "aqt.webview", line 50, in cmd
  File "aqt.webview", line 157, in _onCmd
  File "aqt.webview", line 680, in _onBridgeCmd
  File "aqt.hooks", line 5415, in call
  File "/home/admin/.local/share/Anki2/addons21/572933442/src/commandparsing.py", line 141, in expanded_on_bridge_cmd
    open_editor(mw, int(cmd[15:]))
  File "/home/admin/.local/share/Anki2/addons21/572933442/src/dialogs/editor.py", line 51, in open_editor
    dialog = EditDialog(mw, note)
  File "/home/admin/.local/share/Anki2/addons21/572933442/src/dialogs/editor.py", line 64, in __init
    self.form.setupUi(self)
  File "_aqt.forms.editcurrent_qt6", line 36, in setupUi
AttributeError: 'EditDialog' object has no attribute 'setCentralWidget'
```

I tried looking a bit into it but honestly I'm lost lol

(I'm sorry I'm reporting a lot of issues but this addon is the base of my work routine :sweat_smile: )

**Comment by OuraN2O** [comment]
Oh okay that's cool ! I'm on linux but when you have something somewhat prepared for it I'd be glad to test it

**Comment by Vilhelm-Ian** [comment]
@OuraN2O I can give you a build for linux. But the app image is 200 mb. If you are using arch I think I can share the same build

**Comment by OuraN2O** [comment]
Yes I'm using arch, do you want my mail or something ?

**Comment by abhishek7786** [comment]
@Vilhelm-Ian I'm getting the same error; Is it fixed now; or is there any quick fix which I can apply; Any help is appreciated


Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: macOS-14.1.1-arm64-arm-64bit

Traceback (most recent call last):
  File "aqt.webview", line 50, in cmd
  File "aqt.webview", line 160, in _onCmd
  File "aqt.webview", line 689, in _onBridgeCmd
  File "_aqt.hooks", line 5416, in __call__
  File "/Users/abhishekdwivedi/Library/Application Support/Anki2/addons21/572933442/src/command_parsing.py", line 141, in expanded_on_bridge_cmd
    open_editor(mw, int(cmd[15:]))
  File "/Users/abhishekdwivedi/Library/Application Support/Anki2/addons21/572933442/src/dialogs/editor.py", line 51, in open_editor
    dialog = EditDialog(mw, note)
  File "/Users/abhishekdwivedi/Library/Application Support/Anki2/addons21/572933442/src/dialogs/editor.py", line 64, in __init__
    self.form.setupUi(self)
  File "_aqt.forms.editcurrent_qt6", line 36, in setupUi
AttributeError: 'EditDialog' object has no attribute 'setCentralWidget'

**Comment by Vilhelm-Ian** [comment]
sorry I have been busy. i will take a look at it.

**Comment by Vilhelm-Ian** [comment]
@OuraN2O @abhishek7786  I fixed it

**Comment by Vilhelm-Ian** [comment]
can you test the latest commit

**Comment by OuraN2O** [comment]
> can you test the latest commit

Hey ! Thx for looking to it. I see that responsiveness of the editor dialog doesn't work (see my screenshot)
![image](https://github.com/user-attachments/assets/b6e88071-d851-48ab-b38d-37e60d814fce)

**Comment by abhishek7786** [comment]
Hi, Thanks for the prompt reply.
Tested new commit.
Issue is fixed, Now I can search the card and edit it too.

( small pain point -> After clicking the edit icon When card gets open in browser window, card is very small size, makes editing card bit difficult, refer below for the detail)

As far as this issue is concerned it is fixed now.

![image](https://github.com/user-attachments/assets/6b7258c5-df1c-4998-9c41-240a0a2150fb)

**Comment by curious58** [comment]
Hi! 

I also have the same problem. I can't edit a note after searching in the search bar of the add-on. I get this error:

Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Windows-10-10.0.22631

Traceback (most recent call last):
  File "aqt.webview", line 50, in cmd
  File "aqt.webview", line 160, in _onCmd
  File "aqt.webview", line 689, in _onBridgeCmd
  File "_aqt.hooks", line 5416, in __call__
  File "C:\Users\shiel\AppData\Roaming\Anki2\addons21\572933442\src\command_parsing.py", line 141, in expanded_on_bridge_cmd
    open_editor(mw, int(cmd[15:]))
  File "C:\Users\shiel\AppData\Roaming\Anki2\addons21\572933442\src\dialogs\editor.py", line 51, in open_editor
    dialog = EditDialog(mw, note)
  File "C:\Users\shiel\AppData\Roaming\Anki2\addons21\572933442\src\dialogs\editor.py", line 64, in __init__
    self.form.setupUi(self)
  File "_aqt.forms.editcurrent_qt6", line 36, in setupUi
AttributeError: 'EditDialog' object has no attribute 'setCentralWidget'



May I know how I can fix this? Thank you!

**Comment by Vilhelm-Ian** [comment]
@curious58 pull the latest commit from github. Or download it as a zip and put it in your anki addons folder

**Comment by curious58** [comment]
I'm so sorry but I'm not familiar with doing this, which commit should I download? May I ask for a link?

Thank you!

**Comment by OuraN2O** [comment]
Hi, go on the addon page, then "Code" (the green button), then "Download zip".
![image](https://github.com/user-attachments/assets/e38803f4-7652-43f7-9a6e-9bceda5010b9)
When you have the zip, unzip it and copy paste the files in the addon folder (you can know where it by going in anki > tools > addon > click on the addon > view files)

**Comment by curious58** [comment]
Problem fixed! Thank you so much!
