### ISSUE TITLE
Fail to open

### ISSUE THREAD

**Issue by OuraN2O** [Vilhelm-Ian/anki-search-inside-add-card#21]
**Describe the bug**
Opening anki shows that the addon was unable to start

**To Reproduce**
1. Open anki

**Error message**
`Anki 24.11 (87ccd24e) (src) (ao)
Python 3.12.8 Qt 6.7.3 PyQt 6.7.1
Platform: Linux-6.6.62-gentoo-dist-x86_64-AMD_Ryzen_5_7520U_with_Radeon_Graphics-with-glibc2.40

When loading Searching PDF Reading  Note-Taking in Add Dialog - Qt6 port:
Traceback (most recent call last):
  File "/home/admin/.local/share/Anki2/addons21/572933442/src/notes.py", line 32, in <module>
    from .models import SiacNote, IndexNote, NoteRelations
  File "/home/admin/.local/share/Anki2/addons21/572933442/src/models.py", line 28, in <module>
    from .markdown import markdown
  File "/home/admin/.local/share/Anki2/addons21/572933442/src/markdown/__init__.py", line 29, in <module>
    from .core import Markdown, markdown, markdownFromFile  # noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/.local/share/Anki2/addons21/572933442/src/markdown/core.py", line 26, in <module>
    from . import util
  File "/home/admin/.local/share/Anki2/addons21/572933442/src/markdown/util.py", line 85, in <module>
    INSTALLED_EXTENSIONS = metadata.entry_points().get('markdown.extensions', ())
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'EntryPoints' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/aqt/addons.py", line 250, in loadAddons
    __import__(addon.dir_name)
  File "/home/admin/.local/share/Anki2/addons21/572933442/__init__.py", line 4, in <module>
    from . import src
  File "/home/admin/.local/share/Anki2/addons21/572933442/src/__init__.py", line 51, in <module>
    from .index.indexing import build_index
  File "/home/admin/.local/share/Anki2/addons21/572933442/src/index/indexing.py", line 27, in <module>
    from ..web.html import loadSynonyms
  File "/home/admin/.local/share/Anki2/addons21/572933442/src/web/html.py", line 31, in <module>
    from ..notes import  PDFMark, get_note, _get_priority_list, get_avg_pages_read, get_all_tags, get_related_notes, get_priority, dynamic_sched_to_str, get_read_today_count
  File "/home/admin/.local/share/Anki2/addons21/572933442/src/notes.py", line 37, in <module>
    from models import SiacNote, IndexNote, NoteRelations
  File "/home/admin/.local/share/Anki2/addons21/572933442/src/models.py", line 26, in <module>
    from .web_import import import_webpage
ImportError: attempted relative import with no known parent package`

**Environment (please complete the following information):**
 - OS: Gentoo Linux
 - Anki version 24.11
 
 
 I don't have any flippin' idea why it doesn't work as I copy pasted the anki2/addons21 repository to this computer from another with the same anki version and that was working well

**Comment by OuraN2O** [comment]
Okay I think I found out what was wrong, I installed the app-crypt/mit-krb5 and it works now, somehow it wasn't pulled as a dependency and I was getting the error `ImportError: libgssapi_krb5.so.2: cannot open shared object file: No such file or directory` when trying to run anki from the terminal

**Comment by OuraN2O** [comment]
It's a problem with the anki-bin package on the gentoo repository, doesn't happen when downloading anki from github (after resolving the lib issue)
